### ISSUE TITLE
Add rel option

### ISSUE THREAD

**Issue by vicmosin** [yarri/LinkFinder#1]
It would be nice to have set html's rel attribute via settings. For example, to get a link: 
`<a href="some" rel="nofollow">link</a>`

**Comment by yarri** [comment]
At the moment you can specify a custom link_template. See the following example:

``` php
$lf = new LinkFinder(array(
  'link_template' => '<a href="%href%" rel="nofollow">%url%</a>'
));
echo $lf->process($some_plain_text);
```

Is it ok for you?

**Comment by vicmosin** [comment]
Yes, I did it so.. But since you provide such a library, I think you should support all of the available attributes described in specs..

**Comment by yarri** [comment]
Ok, this sounds good. But since there are quite a lot attributes allowed in <a> element (see http://www.w3schools.com/tags/tag_a.asp), I think that the API deserves some small revision.

What whould you say about this usage:

``` php
<?php
$lf = new LinkFinder(array(
  // attributes for the <a></a> element
  "attrs" => array(
    "rel" => "nofollow",
    "class" => "shiny-link",
    "data-popup" => "yes",
    // ...
  ),

  // attributes for the <a href="mailto:...."></a> element
  "mailto_attrs" => array(
    "class" => "shiny-email",
    // ...
  ),

  // other options
  "escape_html_entities" => false,
  // ...
));
```

**Comment by vicmosin** [comment]
Yeah, it's much better since it will allow custom data-\* attributes

**Comment by yarri** [comment]
Done. Download the latest version and let me know if it fits your needs.

You may need to remove a custom template from your code, because the default template has been changed a bit (but the old form is working in the old way).

**Comment by vicmosin** [comment]
Cool. Could you push it to composer as a v2 or something?

**Comment by yarri** [comment]
I just added tags v1.0 and v2.0.
