### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by playinteractive** [yarri/LinkFinder#2]
Hi, this class is great, thanks. Now it finds links like these:

http://www.domain.com
www.domain.com

But maybe you can improve it in the future if also detects:

domain.com
subdomain.domain.com

You'd may add a list of domain extensions.

Regards.

**Comment by yarri** [comment]
Thank you for your suggestion.

My intention was to avoid false URLs detections. For example in "i like indian food.how about you." there is something which looks like an domain name but it is not: "food.how"

But of course there is a bunch of commonly used top level domains (com, net, org, us, co.uk...) for which the LinkFinder could provide auto link detection even without "www." prefix.

I'll do it... :)

**Comment by playinteractive** [comment]
Great @yarri! Many thanks.

**Comment by yarri** [comment]
I've finished it. It's on the master. Not yet tagged with a version. You can try it by installing a development version:

composer require yarri/link-finder dev-master

Check it out and let me know how it's working.

**Comment by playinteractive** [comment]
I'll check it

**Comment by playinteractive** [comment]
It works great, good job yarri!

**Comment by yarri** [comment]
This function is included in version 2.2
