### ISSUE TITLE
URL valid characters

### ISSUE THREAD

**Issue by playinteractive** [yarri/LinkFinder#3]
Hey yarri, I've found another issue. Try with this URL:

http://domain.com/?var=[ID]

In this case [ID] is outside the link but according to RFC 3986, [ ] are valid characters:

https://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid/1547940#1547940

What do you think?!

**Comment by yarri** [comment]
Thank you. Characters [ ] are now valid for URLs.
